//MARK: - Advertisements == Struct, where was added the specific car models(examples) for following advertisements.

struct Advertisements {
    
    let carModels = [
        
        CarModel(photosName: ["a4_1", "a4_2", "a4_3", "a4_4", "a4_5", "a4_6"] , year: 2018, selector: .automatic, engineVolume: 2.0, mileage: 126000, priceByn: 78734, dascription: "The Best car! White! Beautifull! Without any problems", publicDate: "29 октября", reloadDate: "31 октября", power: 180, fuelTakes: 7.2, color: "белый", marks: .vin,  engineType: .gasoline, bodyType: .sedan, carName: .audi4, city: .Brest, complectation: [.abs, .backParctronics, .esp , .lightSensor, .rhainSensor], wheelsDrive: .forward, change: [.audi5,]),
        
        CarModel(photosName: ["a6_2", "a6_3", "a6_4", "a6_5", "a6_6", "a6_1"], year: 2018, selector: .automatic, engineVolume: 3.0, mileage: 60500, priceByn: 155000, dascription: "This is an amazing bussines sedan! Carefurly its Powerfull!", publicDate: "25 октября", reloadDate: "31 октября", power: 320, fuelTakes: 8.8, color: "черный", marks: .topVin, engineType: .gasoline, bodyType: .sedan, carName: .audi6, city: .Hrodno, complectation: [.abs, .backParctronics, .climatControl, .cruiseControl, .esp, .lightSensor, .rhainSensor, .panoramedRoof], wheelsDrive: .plugInFull, change: [.audi7, .audi8]),
        
        CarModel(photosName: ["a8_1", "a8_2", "a8_3", "a8_4", "a8_5", "a8_6", "a8_7"], year: 2018, selector: .automatic, engineVolume: 3.0, mileage: 108000, priceByn: 201300, dascription: "Excellent condition! Originale mileage! Serviced only by an autoriced dealer!", publicDate: "05 ноября", reloadDate: "05 ноября", power: 285, fuelTakes: 5.6, color: "черный", marks: .none, engineType: .disel, bodyType: .sedan, carName: .audi8, city: .Minsk, complectation: [.abs, .backParctronics, .climatControl, .cruiseControl, .engineAutoStart, .esp, .headParctronics, .immobilaizer, .lightSensor, .panoramedRoof, .rhainSensor], wheelsDrive: .plugInFull, change: [.none]),
        
        CarModel(photosName: ["audi80_1", "audi80_2", "audi80_3", "audi80_4", "audi80_5"], year: 1989, selector: .mechanic, engineVolume: 1.8, mileage: 430000, priceByn: 7700, dascription: "Машина- в отличном состоянии! Как внешне так и технически. Все расходники меняются во время.", publicDate: "10 декабря", reloadDate: "10 декабря", power: 113, fuelTakes: 8.0, color: "белый", marks: .none, engineType: .gasoline, bodyType: .sedan, carName: .audi80, city: .Vitebsk, complectation: [.abs,.esp], wheelsDrive: .forward, change: [.none]),
        
        CarModel(photosName: ["etron_1", "etron_2", "etron_3", "etron_4"], year: 2022, selector: .automatic, engineVolume: 0, mileage: 21000, priceByn: 372000, dascription: "Из Германии, покупали для себя, в эксплуатации чуть меньше года, новая зимняя резина на дисках, хорошая комплектация(пневма, ночное виденье, вентиляция, массаж, панорама и др), весь перед, зеркала, канты, задний бампер в бронепленке, запас хода летом 350-370 км, зимой на процентов 20-25 меньше, авто на учете.", publicDate: "11 декабря", reloadDate: "11 декабря", power: 503, fuelTakes: 0, color: "черный", marks: .vin, engineType: .electric, bodyType: .suv5, carName: .audiEtronS, city: .Minsk, complectation: [.abs, .backParctronics,.climatControl,.cruiseControl,.engineAutoStart,.esp,.headParctronics,.immobilaizer,.lightSensor,.panoramedRoof,.rhainSensor], wheelsDrive: .plugInFull, change: [.none]),
        
        CarModel(photosName: ["audi90_1", "audi90_2", "audi90_3", "audi90_4", "audi90_5", "audi90_6"], year: 1987, selector: .mechanic, engineVolume: 2.3, mileage: 478000, priceByn: 11500, dascription: "Простой надежный автомобиль. Каждый день на ходу. Легенда 80-х!", publicDate: "10 декабря", reloadDate: "10 декабря", power: 133, fuelTakes: 8.0, color: "синий", marks: .none, engineType: .gasoline, bodyType: .sedan, carName: .audi90, city: .Mohilev, complectation: [.esp,.immobilaizer], wheelsDrive: .forward, change: [.audi4])
        ]
}
